- ./:
    - README.md:
        - description: README file
          check: MatchFileFragment
          options:
            fragment: 'trinket.io'
            count: 1
            exact: true
    - main.py:
        - description: Change the value of n on line 8
          check: MatchFileFragment
          options:
            fragment: 'n = 20'
            count: 0
            exact: true



      
