- ./:
    - README.md:
        - description: Add Trinket link to README.md
          check: MatchFileFragment
          options:
            fragment: 'trinket.io'
            count: 1
            exact: true
    - config/main.py:
        - description: Change the value of n on line 11
          check: MatchFileFragment
          options:
            fragment: 'n = 20'
            count: 0
            exact: true
        - description: Change the value of frame_rate on line 13
          check: MatchFileFragment
          options:
            fragment: 'frame_rate = 10'
            count: 0
            exact: true
        - description: Change the value of size on line 15
          check: MatchgitFileFragment
          options:
            fragment: 'size = vector(20, 0.5, 5)'
            count: 0
            exact: true
        - description: Change the value of canvas_color on line 18
          check: MatchFileFragment
          options:
            fragment: 'canvas_color = vector(0, 0, 1)'
            count: 0
            exact: true
        - description: Change the value of sconeds_to_helix on line 21
          check: MatchFileFragment
          options:
            fragment: 'seconds_to_helix = 5'
            count: 0
            exact: true



      
