setup: |
  poetry install
  echo "Setup complete!"
---
- hello_world.py:
    - description: Complete all TODOs
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Call the say_hello function
      check: MatchFileFragment
      options:
        fragment: "say_hello("
        count: 2
    - description: Call the say_hello_color function
      check: MatchFileFragment
      options:
        fragment: "say_hello_color("
        count: 2

