# Basic workflow
name: build

# Controls when the action will run
# Workflow begins with push or PR events
# Focuses on the master branch only
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: 
  contents: write

# Create one single job
# This job performs all necessary checks
jobs:
  build:
    # Use the latest version of Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Performs all actions on different versions of Python
        python-version: ["3.10"]
    # Define the workflow steps
    steps:
        # Setup Python for the current language version
        - name: Setup Python ${{ matrix.python-version }}
          if: always()
          uses: actions/setup-python@v1
          with:
            python-version: ${{ matrix.python-version }}
        # Install pip
        - name: Install Pip
          if: always()
          run: |
            pip install -U pip
        # Run the Python program
        # - name: Run Python Program
        #   if: always()
        #   run: python -c 'f = open("love.py", "w"); f.write("I love you!"); f.close()'
        # Attempt commit
        - uses: actions/checkout@v3
        - name: Create report file
          run: echo "heroes live here" > report.txt
        - name: Commit report
          run: |
            git config --global user.name 'howshekilledit'
            git config --global user.email 'howshekilledite@users.noreply.github.com'
            git add .
            git commit -am "write text to report"
        # Run GatorGrader: see config/gatorgrade.yml
        # - name: Checkout repository
        #   uses: actions/checkout@v3
        #   with: 
        #     fetch-depth: '0'
        - name: Run GatorGrader with GatorGrade
          if: always()
          run:  |
            pip install gatorgrade
            gatorgrade --config gatorgrade.yml
